# -*- coding: utf-8 -*-
"""DepressionEMO_LabelStripping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17IL48FP6NA2s5l5YrVfuMtvsCMUyrvIP
"""

import json
import gc
import torch
from tqdm.notebook import tqdm

"""### Stripping labels from json file"""

def read_list_from_json_file(file_path):
  with open(file_path, 'r') as f:
    return [json.loads(line) for line in f]

def write_list_to_json_file(file_path, data, file_access='a'):
    with open(file_path, file_access) as f:
        if isinstance(data, list):
            for item in data:
                f.write(json.dumps(item) + '\n')
        else:
            #so it works when writing the new labels in as well
            f.write(json.dumps(data) + '\n')

input_file = '/content/final_dataset.json'
dataset = read_list_from_json_file(input_file)

for item in dataset:
  if 'feelings' in item:
    del item['feelings']
    del item['upvotes']

output_file = '/content/final_dataset_nolabels.json'
write_list_to_json_file(output_file, dataset)

print(f"Processed {len(dataset)} items. Saved to {output_file}")